#!/usr/bin/with-contenv bash

# If config file exists, start daemon
if [ -f /etc/quagga/ospfd.conf ] ; then
    echo "Starting Quagga (ospfd)"

    exec \
        /usr/sbin/ospfd
else
    # Otherwise sleep for a while...
    sleep 60
fi
