#!/usr/bin/with-contenv bash

# If config file exists, start daemon
if [ -f /etc/quagga/babeld.conf ] ; then
    echo "Starting Quagga (babeld)"

    exec \
        /usr/sbin/babeld
else
    # Otherwise sleep for a while...
    sleep 60
fi
