#!/usr/bin/with-contenv bash

# If config file exists, start daemon
if [ -f /etc/quagga/ripngd.conf ] ; then
    echo "Starting Quagga (ripngd)"

    exec \
        /usr/sbin/ripngd
else
    # Otherwise sleep for a while...
    sleep 60
fi
